// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9Nmnq_w3HHWA2SHI2muGO7HkyW33udA',
    appId: '1:971238366958:web:dc08a366061e8355ad9dff',
    messagingSenderId: '971238366958',
    projectId: 'techsovlev1',
    authDomain: 'techsovlev1.firebaseapp.com',
    databaseURL: 'https://techsovlev1-default-rtdb.firebaseio.com',
    storageBucket: 'techsovlev1.firebasestorage.app',
    measurementId: 'G-R916K70EWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhJC5j4BFxYq6cYO5c2QeUC-J7d5IAaU0',
    appId: '1:971238366958:android:58beb79a516e70eead9dff',
    messagingSenderId: '971238366958',
    projectId: 'techsovlev1',
    databaseURL: 'https://techsovlev1-default-rtdb.firebaseio.com',
    storageBucket: 'techsovlev1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZOVnhlixEW26t-ik4XfG92DhpCUrTZA',
    appId: '1:971238366958:ios:513f8d04e344c173ad9dff',
    messagingSenderId: '971238366958',
    projectId: 'techsovlev1',
    databaseURL: 'https://techsovlev1-default-rtdb.firebaseio.com',
    storageBucket: 'techsovlev1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZOVnhlixEW26t-ik4XfG92DhpCUrTZA',
    appId: '1:971238366958:ios:f9aa7c3a705c3ebead9dff',
    messagingSenderId: '971238366958',
    projectId: 'techsovlev1',
    databaseURL: 'https://techsovlev1-default-rtdb.firebaseio.com',
    storageBucket: 'techsovlev1.firebasestorage.app',
    iosBundleId: 'com.example.sagu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM9Nmnq_w3HHWA2SHI2muGO7HkyW33udA',
    appId: '1:971238366958:web:a62b994d7648f8f5ad9dff',
    messagingSenderId: '971238366958',
    projectId: 'techsovlev1',
    authDomain: 'techsovlev1.firebaseapp.com',
    databaseURL: 'https://techsovlev1-default-rtdb.firebaseio.com',
    storageBucket: 'techsovlev1.firebasestorage.app',
    measurementId: 'G-LPVBKMLJMJ',
  );

}